### ISSUE TITLE
ObjectId validator

### ISSUE THREAD

**Issue by ahmadyazdanii** [ahmadyazdanii/Ticket-Management-API#2]
### Description
we need an objectId validator for routes based on the default Nest.js pipe validator.

### Current State
no one route can not handle the wrong format of objectId type fields and, caused to return an `internal server` error!

### Tasks

- [ ] create an ObjectId class/decorator validator
- [ ] use the validator for routes that needs
- [ ] update unit/e2e tests that are related to the internal server error or any type of errors generated by these changes.
