### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ahmadyazdanii** [ahmadyazdanii/Ticket-Management-API#4]
### Description
create a good readme for the project.

### Current State
default Nest.js readme is using.

### Tasks
- [ ] Append Description section
- [ ] Append Run section
- [ ] Append Deploy section
- [ ] Append Contribution section
